
language: perl

env:
  global:
    secure: ZN21ihuhGsPo0HAGvdBXUr77ybU20IZZqPn5oKJZCeTaLKHIET9ZfvAuTj42fOAMumiZBk9AjdNtHuMUaEXtI6BnVk86kDiwj/H2uwcIPUwNKDYIxhljxD3uqH5UniBRVcN4Ngu2o/jXo3dNeMwfI0kpTtM10+/8VMqpPf92Bnk=

install:
  - cd ..
  - git clone https://github.com/kbase/jars
  - git clone https://github.com/kbaseIncubator/module_builder
  - cd module_builder
  - git checkout develop
  - make
  - cd ../service_test
  - cpanm --verbose --notest JSON::RPC::Client
  - cpanm --verbose --notest Exception::Class

script:
  - make